### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by icebob** [Ferroman/moleculer-auth#1]
Hi @Ferroman,

are you using & maintain this auth libs for Moleculer?

**Comment by Ferroman** [comment]
Unfortunately I don't have enough time to maintain it as it should be. Why?

**Comment by icebob** [comment]
I plan to make a similar official auth lib. And if you don't want to continue these modules, maybe you can transfer it to under moleculer org and I will try to continue & upgrade to 0.13
